In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
import numpy as np

<img src="Images/panda.png"/>

In [7]:
#Turning this to a numpy array
from matplotlib.image import imread as im

In [10]:
panda = im("Images/panda.png")

In [11]:
type(panda)

numpy.ndarray

In [12]:
print(panda)

[[[0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  ...
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]]

 [[0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  ...
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]]

 [[0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  [0.05490196 0.10588235 0.06666667]
  ...
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]
  [0.16470589 0.12941177 0.09411765]]

 ...

 [[0.13333334 0.07450981 0.05490196]
  [0.12156863 0.0627451  0.04313726]
  [0.10980392 0.05098039 0.03137255]
  ...
  [0.02745098 0.02745098 0.03529412]
  [0.02745098 0.02745098 0.03529412]
  [0.02745098 0.02745098 0.03529412]]

 [[0.13333334 0.07450981 0.05490196]
  [0.12156863 0.0627451  0.04313726]
