# Numpy Learning

In [1]:
import numpy as np

In [2]:
#for complexity
import pandas as pd

## Datatypes and attributes

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[2.3,4.0,6.5],
             [3.8,5.0,7.5]])

a3 = np.array([[[5,6,7],
              [8,9,10]],
             [[11,12,13],
              [14,15,16]],
              [[1,2,3],
              [3,4,5]]])

In [6]:
a2

array([[2.3, 4. , 6.5],
       [3.8, 5. , 7.5]])

In [7]:
a3

array([[[ 5,  6,  7],
        [ 8,  9, 10]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[ 1,  2,  3],
        [ 3,  4,  5]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(3, 2, 3)

In [11]:
a1.ndim,a2.ndim,a3.ndim


(1, 2, 3)

In [12]:
df = pd.DataFrame(a2)

In [13]:
df

0    1    2
0  2.3  4.0  6.5
1  3.8  5.0  7.5

In [14]:
test = np.ones((3,2,4), 'int64')

In [15]:
test

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [16]:
np.random.seed(1)
#trying = np.zeroes()
#trying = np.arange(0,3)
trying = np.random.randint(2,10,size = (3,3))
#trying = np.random.random((2,3))
#trying = np.random.rand(2,3)
trying

array([[7, 5, 6],
       [2, 9, 3],
       [5, 7, 9]], dtype=int32)

In [17]:
np.unique(trying)

array([2, 3, 5, 6, 7, 9], dtype=int32)

In [18]:
a3[:3, :1, :1]

array([[[ 5]],

       [[11]],

       [[ 1]]])

In [19]:
a3[:,:1,:3]

array([[[ 5,  6,  7]],

       [[11, 12, 13]],

       [[ 1,  2,  3]]])

## Manipulating Data

### Arithmetic

In [20]:
a1 + np.ones(3, 'int64')

array([2, 3, 4])

In [21]:
# useless basic math

### Aggregation

In [22]:
List = [1, 2, 3]

In [23]:
sum(List)

6

In [24]:
np.sum(List)

np.int64(6)

(`np.sum()`) on numpy's datatypes and (`sum()`) on python's datatypes

In [25]:
mass = np.random.random(100000)

In [47]:
mass[:10]

array([0.23608898, 0.39658073, 0.38791074, 0.66974604, 0.93553907,
       0.84631092, 0.31327352, 0.52454816, 0.44345289, 0.22957721])

In [45]:
%timeit sum(mass)

9.21 ms ± 215 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [46]:
%timeit np.sum(mass)

31.6 μs ± 801 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [29]:
#insane time difference GAHDAMN

In [30]:
a2

array([[2.3, 4. , 6.5],
       [3.8, 5. , 7.5]])

In [31]:
#np.mean()
#np.max()
#np.min()
#np.std()
#np.var()

In [32]:
#now we have fun

In [33]:
high = np.array([200,10000,100,35,29969,3])

In [34]:
low = np.array([1,2,3,4,5,6])

In [35]:
np.mean(high), np.mean(low)

(np.float64(6717.833333333333), np.float64(3.5))

In [36]:
np.std(high), np.std(low)

(np.float64(11010.725731707647), np.float64(1.707825127659933))

In [37]:
np.var(high), np.var(low)

(np.float64(121236081.1388889), np.float64(2.9166666666666665))

### Reshape & Transpose

In [38]:
a2

array([[2.3, 4. , 6.5],
       [3.8, 5. , 7.5]])

In [39]:
a2_reshape = a2.reshape(3,2,1)

In [40]:
a2_reshape

array([[[2.3],
        [4. ]],

       [[6.5],
        [3.8]],

       [[5. ],
        [7.5]]])

In [41]:
a3

array([[[ 5,  6,  7],
        [ 8,  9, 10]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[ 1,  2,  3],
        [ 3,  4,  5]]])

In [42]:
a2_reshape*a3

array([[[11.5, 13.8, 16.1],
        [32. , 36. , 40. ]],

       [[71.5, 78. , 84.5],
        [53.2, 57. , 60.8]],

       [[ 5. , 10. , 15. ],
        [22.5, 30. , 37.5]]])

In [43]:
a2.T

array([[2.3, 3.8],
       [4. , 5. ],
       [6.5, 7.5]])

In [44]:
a2

array([[2.3, 4. , 6.5],
       [3.8, 5. , 7.5]])

In [50]:
np.random.seed(1)

mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (5,3))

In [54]:
mat1 , mat2


(array([[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6],
        [9, 2, 4],
        [5, 2, 4]], dtype=int32),
 array([[2, 4, 7],
        [7, 9, 1],
        [7, 0, 6],
        [9, 9, 7],
        [6, 9, 1]], dtype=int32))

In [55]:
mat1 * mat2

array([[10, 32, 63],
       [35,  0,  0],
       [ 7,  0, 36],
       [81, 18, 28],
       [30, 18,  4]], dtype=int32)

In [65]:
np.random.seed(1)

prices = np.random.randint(5,10, size = (1,3))
prices_df = pd.DataFrame(prices, index = ['price'], columns = ['Nike', 'Adidas', 'Puma'])
prices_df

Nike  Adidas  Puma
price     8       9     5

In [70]:
np.random.seed(1)
sales = np.random.randint(10, size = (4,3))
sales_df = pd.DataFrame(sales, index = ['Mon','Tues','Wed', 'Thurs'], columns = ['Nike','Adidas','Puma'])
sales_df

Nike  Adidas  Puma
Mon       5       8     9
Tues      5       0     0
Wed       1       7     6
Thurs     9       2     4

In [80]:
sales_df.shape, prices_df.shape


((4, 3), (3, 1))

In [78]:
prices_df = prices_df.T

In [79]:
prices_df

price
Nike        8
Adidas      9
Puma        5

In [81]:
np.dot(sales_df, prices_df)

array([[157],
       [ 40],
       [101],
       [110]], dtype=int32)